fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    systemd: 'git://github.com/camptocamp/puppet-systemd.git'
  symlinks:
    qpid: "#{source_dir}"
